name: nix scan
description: scans nix packages for vulnerabilities
author: trev

inputs:
  packages:
    description: nix packages to scan
    required: false
    default: ""

runs:
  using: docker
  image: docker://ghcr.io/spotdemo4/nix-scan:0.0.1
  env:
    ENV_ARGS: ${{ inputs.packages }}
