name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "force"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

concurrency:
  group: release

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        name: Checkout
        uses: spotdemo4/better-checkout@347527b6a5b1c1dba59ad3b66f68b9b0835cb740 # v0.8.0
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          fetch-depth: 0

      - name: Bump
        uses: spotdemo4/bumper@eef9e1c81fe47bc0093d51efb243543ce5f7f2ad # v0.14.5
        with:
          github_token: ${{ steps.checkout.outputs.token }}
          force: ${{ inputs.force }}
          files: |
            action.yaml
            .github/README.md
