name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@5fe5a93e1ff2a6a4cfba1ae7d3f30d0dfed9d1a9 # v1.34.1

      - name: Run checks
        run: nix flake check
