name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@fc128008797d8467f50a419abe60e75c9004d021 # v1.36.1

      - name: Run checks
        run: nix flake check
