name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: spotdemo4/better-checkout@cd29bff8404ecbcb6bf0c0b540d63602c5a2468b # v0.6.0
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          fetch-depth: 0

      - name: Release
        uses: spotdemo4/nix-flake-release@f1a3e206978a7827ac557564507710caf0e91e37 # v0.12.1
        with:
          github_token: ${{ steps.checkout.outputs.token }}
