name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: spotdemo4/better-checkout@a08be04e9f594479a4ac25b1a67d707190dd619e # v0.10.0
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          fetch-depth: 0

      - name: Release
        uses: spotdemo4/flake-release@b55545a5650d7fafdb4751f56999f9fa001655e9 # v0.16.0
        with:
          github_token: ${{ steps.checkout.outputs.token }}
          packages: |
            images.x86_64-linux.default
