name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: spotdemo4/better-checkout@9772c97e43eba14b9cbf29c6e9f8c8121bad5b53 # v0.7.0
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          fetch-depth: 0

      - name: Release
        uses: spotdemo4/nix-flake-release@926a38ad6690de9206f761e4fcb795fef2bd95b3 # v0.13.0
        with:
          github_token: ${{ steps.checkout.outputs.token }}
