name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nix:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@468df9f0e52570a28a9368f4eaee60a8d3847f66 # v1.39.0
        with:
          shell: vulnerable

      - name: Run flake-checker
        run: flake-checker -f

      - name: Run nix-scan
        run: nix-scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  actions:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@468df9f0e52570a28a9368f4eaee60a8d3847f66 # v1.39.0
        with:
          shell: vulnerable

      - name: Run octoscan
        run: octoscan scan .github
